### PR TITLE
Standardize error handling across backend services and frontend auth

### LINKED ISSUE #346: [BUG] Inconsistent error handling between services (UserService returns plain text, signup helpers fail silently)
### **Describe the bug**

Error handling across services is inconsistent.

The messaging service correctly uses a global exception handler and returns structured JSON responses for validation errors and generic failures. However, this pattern is not consistently followed in other parts of the system.

1. The **User Service** still returns plain text messages for domain errors such as `"user not found"` and `"user already exists"` instead of structured JSON responses. This behavior is implemented in `GlobalExceptionHandler.java`.

2. The **sign-up helper functions** in the frontend return silently when Clerk is not loaded. As a result, failures during the sign-up process often appear only as generic alerts rather than proper error responses with meaningful information.

These inconsistencies make error handling unreliable and harder for the frontend to interpret and display meaningful feedback to users.

Affected files:
- `GlobalExceptionHandler.java`
- `utils.ts`

---

### **Steps To Reproduce**

1. Start the backend services.
2. Trigger a domain error in the user service (e.g., attempt to create a user that already exists or request a user that does not exist).
3. Observe that the service returns a plain text error message instead of structured JSON.

For the sign-up helper:

4. Attempt to perform a sign-up action when Clerk is not properly initialized or loaded.
5. Observe that the helper returns silently and the UI only shows a generic alert without structured error details.

---

### **Expected behavior**

All services should return **structured JSON error responses** using a consistent format across the system.

Expected improvements:

- The **User Service** should return structured JSON error objects for domain errors, similar to the messaging service.
- The **sign-up helper functions** should explicitly return or propagate errors when Clerk is not available instead of failing silently.
- Frontend components should receive structured error data that can be properly displayed to the user.

---

### **Screenshots**

N/A

---

### **Additional context**

Files affected:
- `GlobalExceptionHandler.java`
- `utils.ts`

Recommended fixes:

- Update the User Service exception handling to return structured JSON responses for domain errors.
- Ensure `GlobalExceptionHandler` standardizes error responses across services.
- Modify the sign-up helpers so they properly throw or return errors when Clerk is not loaded instead of silently returning.
- Align error handling behavior with the pattern used in the messaging service.

---

### PR DESCRIPTION
**Pull request by F4KER-X**
## Summary
- **User Service**: `GlobalExceptionHandler` now returns structured JSON (`ErrorResponse`) instead of plain text for `UserNotFoundException` and `UserAlreadyExistsException`; `ErrorResponse` model extended with `error`, `message`, and `timestamp` fields
- **Messaging Service**: Replaced inline `HashMap` response builder with a proper `ErrorResponse` record, matching the League/Team service pattern
- **League Service**: `StripeWebhookController` error responses now return structured JSON instead of plain strings
- **Frontend**: Removed silent failures in `sign-up.ts`, `sign-in.ts`, and `sign-up.tsx` — Clerk-not-loaded guards now show user-facing alerts instead of returning silently

## Test plan
- [ ] User Service: hit a missing user endpoint and verify response is `{ "error": "NOT_FOUND", "message": "...", "timestamp": "..." }`
- [ ] User Service: attempt duplicate user creation and verify structured JSON error response
- [ ] Messaging Service: trigger a 404/400 and verify response shape matches League/Team services
- [ ] Stripe webhook: send a request with an invalid signature and verify JSON error response
- [ ] Frontend: test sign-up flow before Clerk has loaded and confirm alert is shown
- [ ] Frontend: test sign-in flow before Clerk has loaded and confirm toast is shown

### CODE REVIEW

File: Frontend/app/(auth)/sign-up.tsx [hunk 1]
```diff
@@ -82,6 +83,7 @@ export default function SignUpScreen() {
     },
     onSuccess: ({ started, values }) => {
       if (!started) {
+        toast("Sign up could not be started. Please try again.");
```
Comment (GianlucaGirardi) [inline Frontend/app/(auth)/sign-up.tsx]: Should the toast message reflect the backend error or be hardcoded?

File: Frontend/utils/sign-in.ts [hunk 2]
```diff
@@ -44,7 +44,10 @@ export const signin = async (
   setActive: SetActive,
   isLoaded: boolean,
 ): Promise<void> => {
-  if (!isLoaded) return;
+  if (!isLoaded) {
+    toast("Sign in unavailable. Please wait a moment and try again.");
```
Comment (GianlucaGirardi) [inline Frontend/utils/sign-in.ts]: Should the toast message reflect the backend error or be hardcoded?

File: Frontend/utils/sign-up.ts [hunk 3]
```diff
@@ -81,6 +81,7 @@ export const startClerkSignUp = async (
   signUp: SignUpResource | undefined,
 ): Promise<boolean> => {
   if (!isLoaded || !signUp) {
+    toast("Sign up unavailable. Please wait a moment and try again.");
```
Comment (GianlucaGirardi) [inline Frontend/utils/sign-up.ts]: Should the toast message reflect the backend error or be hardcoded?

File: Frontend/utils/sign-up.ts [hunk 4]
```diff
@@ -111,6 +112,7 @@ export const completeVerificationAndUpsert = async (
   deleteUserOnError: () => Promise<void>,
 ): Promise<void> => {
   if (!isLoaded || !signUp) {
+    toast("Verification unavailable. Please wait a moment and try again.");
```
Comment (GianlucaGirardi) [inline Frontend/utils/sign-up.ts]: Should the toast message reflect the backend error or be hardcoded?

**Review by GianlucaGirardi — DISMISSED** [review]
Great work, added a small comment regarding the display of toaster messages.

**Review by GianlucaGirardi — APPROVED** [review]
