### PR TITLE
GH-335: [fix] Referee preferences layout shift and black screen in Sports and Regions pages

### LINKED ISSUE #335: [BUG] Referee flow: flickering, layout shifting and black screen on Settings, Sports, and Regions pages
### **Describe the bug**

**Primary issues (visual/UX):**

1. **Settings page flickering** — The API request to check if the user is a referee runs when the Settings page opens. This causes flickering/stuttering as the Referee Preferences section appears or updates once the request completes.

2. **Sports and Regions pages flickering** — Same issue: the API request runs when these pages open, causing the same flickering/stuttering as data loads.

3. **Black page flash on Sports/Regions** — The background gradient logic lives inside the selection component rather than the route. The page opens as a black screen, then the background gradient appears only after the API request completes.

**Root cause:** Referee data is fetched on each page mount instead of being available app-wide. Each page triggers its own API call, leading to loading states and layout shifts.

**Secondary issues:** Pause/Resume lacks confirmation dialog; Form.Section nesting; hardcoded `sports`/`allowedRegions` in registration; scattered state; duplicate header/save logic; ButtonItem BlurView tint; flat route structure.

---

### **Steps To Reproduce**

1. Go to Settings as a signed-in user — observe flickering/stuttering and layout shifts as the Referee Preferences section appears.
2. As a referee, tap Sports or Regions — observe a black screen briefly, then the background gradient and content appears.
3. Repeat navigation to these pages to confirm the pattern.

---

### **Expected behavior**

- Settings page shows Referee Preferences without flickering or layout shifts; referee status is known before the page renders.
- Sports and Regions pages open with the background gradient visible immediately; no black flash.
- No flickering or stuttering from API requests on page open — data is fetched at app level and available when pages mount.

### PR DESCRIPTION
**Pull request by mavmoud**
Fixes stuttering and layout shifting when opening Settings and referee selection pages by centralizing referee data in a context. Fixes black screen on Sports/Regions by moving background into route components. Closes #335.

---

### **Changes Made**
- [x] Added RefereeProvider context for app-wide referee state
- [x] Refactored settings page to use referee context instead of inline API calls
- [x] Added confirmation dialog for Pause/Resume Refereeing (matching `Become a Referee` pattern)
- [x] Fixed Form.Section nesting, Referee Preferences is now standalone
- [x] Removed hardcoded `sports` and `allowedRegions` from `registerAsReferee`
- [x] Extracted useRefereeHeader hook and simplified useRefereeSelection
- [x] Restructured settings routes (profile/edit, referee/regions, referee/sports)
- [x] Fixed black screen on Sports/Regions by moving ContentArea into route components
- [x] Inlined referee selection form into regions and sports pages (removed RefereeSelectionPage)
- [x] Added BlurView tint to ButtonItem (was mistakenly removed)

---
### **How to Test**
1. Sign in as a user
2. Go to Settings and tap Become a Referee, verify no hardcoded sports/regions in API request
3. Verify no flickering or layout shift when reopening settings page and Referee Preferences section appears
4. As a referee, tap Sports or Regions, verify no black screen; background gradient visible immediately
5. Tap Pause Refereeing, verify confirmation dialog appears before toggle

---

### **Environment**
- **Device:** iOS Simulator / iOS Device

---

### **Checkout**
- [x] SonarQube Pass

---

### **Additional Notes**
- RefereeSelectionPage component eliminated; Form + Multiselect inlined into regions and sports route pages

### CODE REVIEW

File: Frontend/hooks/use-referee-header.tsx [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+): Promise<void> {
+    if (!canSave) {
+        alert(`Please select at least one ${title.toLowerCase()}`);
+        return;
+    }
+    try {
+        await saveItems();
+        router.back();
+    } catch (error) {
+        console.error(`Failed to update ${title.toLowerCase()}:`, error);
```
Comment (RenalWasouf) [inline Frontend/hooks/use-referee-header.tsx]: Please use our custom logger (using createScopedLog).

**Review by RenalWasouf — APPROVED** [review]
Great job
