### PR TITLE
Fix unauthenticated user creation endpoint and self-demote IDOR vulnerability

### LINKED ISSUE #345: [BUG] Security issues: public user creation endpoint and unsafe self-demote route
### **Describe the bug**

There are two security issues that were previously identified but remain unresolved.

1. The API gateway whitelist still allows access to `/api/v1/user/create` without authentication. This means users can create accounts without going through the intended authentication flow.

2. The `self-demote` route in the team service takes `userId` directly from the URL instead of retrieving the user identity from the authentication context. This could allow a malicious user to demote another user if they know or guess their ID.

These issues weaken the security strategy of the system.

Affected files:
- `PublicEndpoints.java`
- `TeamController.java`

---

### **Steps To Reproduce**

1. Start the backend services and API gateway.
2. Send a request to `/api/v1/user/create` without authentication.
3. Observe that the request is allowed even though it should require authentication.

For the self-demote route:

4. Authenticate as a user.
5. Call the self-demote endpoint and manually modify the `userId` in the request URL to another user’s ID.
6. Observe that the request may succeed even though the action should only apply to the authenticated user.

---

### **Expected behavior**

- The endpoint `/api/v1/user/create` should not be accessible through the gateway without proper authentication or validation rules.
- The self-demote route should retrieve the user identity from the authentication context rather than accepting a `userId` from the URL.
- Authorization checks should ensure users can only perform actions on their own account unless they have explicit permissions.

---

### **Screenshots**

N/A

---

### **Additional context**

Files affected:
- `PublicEndpoints.java` (API Gateway)
- `TeamController.java` (Team Service)

Recommended fixes:
- Remove `/api/v1/user/create` from the gateway whitelist or restrict it appropriately.
- Modify the self-demote endpoint to obtain the user identity from the authentication principal instead of the route parameter.
- Add proper authorization validation to ensure users cannot modify other users’ roles.

---

### PR DESCRIPTION
**Pull request by F4KER-X**
## Summary
- Remove `/api/v1/user/create` from the API Gateway public whitelist — the Clerk JWT is available at call time since `setActive` is awaited before `upsertUser.mutateAsync`, so this endpoint no longer needs to be unauthenticated
- Fix IDOR vulnerability in self-demote route: remove `userId` from the URL path and read the caller's identity from the JWT via `CurrentUserProvider` instead, preventing users from demoting arbitrary members

## Security impact
- **Gateway whitelist** — previously any unauthenticated request could hit the user creation endpoint; now a valid Bearer token is required
- **Self-demote IDOR** — previously `POST /{teamId}/members/self-demote/{userId}` accepted an arbitrary `userId` from the URL; the new route `POST /{teamId}/members/self-demote` derives the user ID from the authenticated JWT

## Test plan
- [ ] Sign up a new user end-to-end and confirm the profile is created without errors (verifies the JWT is attached when `/user/create` is called)
- [ ] Attempt to call `POST /api/v1/user/create` without a Bearer token — expect 401
- [ ] As a team member, call `POST /{teamId}/members/self-demote` and confirm only your own role is demoted
- [ ] Confirm no existing self-demote callers in the frontend pass a `userId` segment in the URL

### CODE REVIEW

File: Backend/go-league-service/src/main/java/com/game/on/go_league_service/league/dto/ExploreMatchesRequest.java
Comment (GianlucaGirardi) [inline Backend/go-league-service/src/main/java/com/game/on/go_league_service/league/dto/ExploreMatchesRequest.java:1]: good job adding the validation

File: Backend/go-league-service/src/main/java/com/game/on/go_league_service/league/service/ExploreService.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+
+    private LeagueMatchResponse toResponse(LeagueMatch match) {
+        return new LeagueMatchResponse(
+                match.getId(),
+                match.getLeague().getId(),
+                match.getStatus(),
+                match.getHomeTeamId(),
+                match.getAwayTeamId(),
+                null,
+                null,
```
Comment (GianlucaGirardi) [inline Backend/go-league-service/src/main/java/com/game/on/go_league_service/league/service/ExploreService.java:38]: why are these fields NULL?

File: Backend/go-messaging-service/src/main/java/com/game/on/go_messaging_service/exception/GlobalExceptionHandler.java
Comment (GianlucaGirardi) [inline Backend/go-messaging-service/src/main/java/com/game/on/go_messaging_service/exception/GlobalExceptionHandler.java:1]: Good initiative

**Review by GianlucaGirardi — DISMISSED** [review]

File: Backend/go-league-service/src/main/java/com/game/on/go_league_service/league/service/ExploreService.java (hunk 1 above)
Comment (F4KER-X) [reply Backend/go-league-service/src/main/java/com/game/on/go_league_service/league/service/ExploreService.java:38]: scores are always null at this point until the games are finished.

**Review by AsimRahman88 — DISMISSED** [review]
Approved. Great work as this will help the project move forward and be closer to the final product. Also, it resolved issues from before that needed to be fixed.

**Review by GianlucaGirardi — DISMISSED** [review]

**Review by AsimRahman88 — DISMISSED** [review]
approved

**Review by AsimRahman88 — APPROVED** [review]
Approved.
